### ISSUE TITLE
Import error in web application with Django 1.3.1

### ISSUE THREAD

**Issue by antot** [cfedermann/Appraise#43]
Appraise requires Django >=1.3 but the web app doesn't work with 1.3.1.

When pointing the browser to "http://127.0.0.1:8000/appraise/" with the server running, I get the following error:

ImportError at /appraise/

cannot import name patterns

Request Method:     GET
Request URL:    http://127.0.0.1:8000/appraise/
Django Version:     1.3.1
Exception Type:     ImportError
Exception Value:    

cannot import name patterns

Exception Location:     /home/a/software/Appraise-Software/appraise/../appraise/urls.py in <module>, line 7
Python Executable:  /usr/bin/python
Python Version:     2.7.6
Python Path:    

['/home/a/software/Appraise-Software/appraise',
 '/usr/local/lib/python2.7/dist-packages/langid-1.1.4dev-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gst-0.10',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

Server time:    Wed, 27 Aug 2014 16:01:59 +0200
